# action.yml
name: 'AWS Elastic Beanstalk cli'

author: Habid Manzur

description: 'Provide eb cli commands'

branding:
  icon: 'terminal'  
  color: 'white'
  
inputs:
  command:  # id of input
    description: 'eb <command>'
    required: true
    default: 'deploy'
  
  dir:  # dir of files
    description: 'cd <dir>'
    required: true
    default: ''
    
  profile:  # eb profile (user)
    description: 'aws config --profile <profile>'
    required: true
    default: ''
    
  region:  # eb region
    description: 'eb region'
    required: true
    default: ''
    
  application_name:  # eb application_name
    description: 'eb application_name'
    required: true
    default: ''
  

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.dir }}
    - ${{ inputs.profile }}
    - ${{ inputs.region }}
    - ${{ inputs.application_name }}
