# action.yml
name: 'AWS Elastic Beanstalk cli'

author: Habid Manzur

description: 'Provide eb cli commands'

branding:
  icon: 'terminal'  
  color: 'white'
  
inputs:
  command:  # id of input
    description: 'eb <command>'
    required: true
    default: 'deploy'
  
  dir:  # dir of files
    description: 'cd <dir>'
    required: true
    default: ''
  

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.dir }}
